// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package sqlc

import (
	"context"
)

const createItem = `-- name: CreateItem :one
INSERT INTO todo_items (
    title,
    description,
    image,
    status
) VALUES (
    $1, $2, $3, $4
) RETURNING id, title, description, image, status, created_at, updated_at, deleted_at
`

type CreateItemParams struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Image       []byte `json:"image"`
	Status      int16  `json:"status"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (TodoItem, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.Title,
		arg.Description,
		arg.Image,
		arg.Status,
	)
	var i TodoItem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Image,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateItem = `-- name: UpdateItem :one
UPDATE todo_items
SET
    title = COALESCE($1, title),
    description = COALESCE($2, description),
    image = COALESCE($3, image),
    status = COALESCE($4, status)
WHERE
    id = $5
    AND deleted_at IS NULL
RETURNING id, title, description, image, status, created_at, updated_at, deleted_at
`

type UpdateItemParams struct {
	Title       *string `json:"title"`
	Description string  `json:"description"`
	Image       []byte  `json:"image"`
	Status      *int16  `json:"status"`
	ID          int32   `json:"id"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (TodoItem, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.Title,
		arg.Description,
		arg.Image,
		arg.Status,
		arg.ID,
	)
	var i TodoItem
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Image,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
