// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TodoItem struct {
	ID          int32  `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	Image       []byte `json:"image"`
	// Status: 1-Doing, 2-Done, 3-Deleted
	Status    int16              `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// Soft delete timestamp: NULL mean not deleted
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
