// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateItem(ctx context.Context, arg CreateItemParams) (TodoItem, error)
	UpdateItem(ctx context.Context, arg UpdateItemParams) (TodoItem, error)
}

var _ Querier = (*Queries)(nil)
